# Generated by Django 4.2.6 on 2023-10-14 16:38

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('class_status', models.CharField(choices=[('First', 'First Class'), ('Second', 'Second Class'), ('Economy', 'Economy Class')], default='First', max_length=20)),
                ('schedule', models.DateField()),
                ('departure_time', models.TimeField(unique=True)),
                ('plat_form', models.PositiveIntegerField()),
                ('station_master', models.ManyToManyField(blank=True, related_name='station_master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
