# Generated by Django 4.2.6 on 2023-10-14 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tstation', '0001_initial'),
        ('tbPlatform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('seat_number', models.PositiveIntegerField(unique=True)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_stop_here', to='tstation.trainstation')),
                ('passenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_starting_here', to='tstation.trainstation')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Train_name', to='tbPlatform.train')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainjourney',
            constraint=models.UniqueConstraint(fields=('train', 'start_station', 'end_station'), name='journey_start_from_end'),
        ),
    ]
